package Ontology.impl;

import Ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultPATIENT_INFORMATION <br>
 * @version generated on Mon Nov 02 00:41:38 WAT 2015 by oyindolapo
 */
public class DefaultPATIENT_INFORMATION extends WrappedIndividualImpl implements PATIENT_INFORMATION {

    public DefaultPATIENT_INFORMATION(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_entry_point
     */
     
    public Collection<? extends WrappedIndividual> getHas_entry_point() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_ENTRY_POINT,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHas_entry_point() {
	   return !getHas_entry_point().isEmpty();
    }

    public void addHas_entry_point(WrappedIndividual newHas_entry_point) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_ENTRY_POINT,
                                       newHas_entry_point);
    }

    public void removeHas_entry_point(WrappedIndividual oldHas_entry_point) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_ENTRY_POINT,
                                          oldHas_entry_point);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_uniqueness
     */
     
    public Collection<? extends WrappedIndividual> getHas_uniqueness() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HAS_UNIQUENESS,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHas_uniqueness() {
	   return !getHas_uniqueness().isEmpty();
    }

    public void addHas_uniqueness(WrappedIndividual newHas_uniqueness) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HAS_UNIQUENESS,
                                       newHas_uniqueness);
    }

    public void removeHas_uniqueness(WrappedIndividual oldHas_uniqueness) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HAS_UNIQUENESS,
                                          oldHas_uniqueness);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_Firstname
     */
     
    public Collection<? extends String> getHas_Firstname() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_FIRSTNAME, String.class);
    }

    public boolean hasHas_Firstname() {
		return !getHas_Firstname().isEmpty();
    }

    public void addHas_Firstname(String newHas_Firstname) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_FIRSTNAME, newHas_Firstname);
    }

    public void removeHas_Firstname(String oldHas_Firstname) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_FIRSTNAME, oldHas_Firstname);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_ID
     */
     
    public Collection<? extends Object> getHas_ID() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_ID, Object.class);
    }

    public boolean hasHas_ID() {
		return !getHas_ID().isEmpty();
    }

    public void addHas_ID(Object newHas_ID) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_ID, newHas_ID);
    }

    public void removeHas_ID(Object oldHas_ID) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_ID, oldHas_ID);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_address
     */
     
    public Collection<? extends String> getHas_address() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_ADDRESS, String.class);
    }

    public boolean hasHas_address() {
		return !getHas_address().isEmpty();
    }

    public void addHas_address(String newHas_address) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_ADDRESS, newHas_address);
    }

    public void removeHas_address(String oldHas_address) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_ADDRESS, oldHas_address);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_age
     */
     
    public Collection<? extends Integer> getHas_age() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_AGE, Integer.class);
    }

    public boolean hasHas_age() {
		return !getHas_age().isEmpty();
    }

    public void addHas_age(Integer newHas_age) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_AGE, newHas_age);
    }

    public void removeHas_age(Integer oldHas_age) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_AGE, oldHas_age);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_allergy
     */
     
    public Collection<? extends String> getHas_allergy() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_ALLERGY, String.class);
    }

    public boolean hasHas_allergy() {
		return !getHas_allergy().isEmpty();
    }

    public void addHas_allergy(String newHas_allergy) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_ALLERGY, newHas_allergy);
    }

    public void removeHas_allergy(String oldHas_allergy) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_ALLERGY, oldHas_allergy);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_educational_level
     */
     
    public Collection<? extends String> getHas_educational_level() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_EDUCATIONAL_LEVEL, String.class);
    }

    public boolean hasHas_educational_level() {
		return !getHas_educational_level().isEmpty();
    }

    public void addHas_educational_level(String newHas_educational_level) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_EDUCATIONAL_LEVEL, newHas_educational_level);
    }

    public void removeHas_educational_level(String oldHas_educational_level) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_EDUCATIONAL_LEVEL, oldHas_educational_level);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_family_history
     */
     
    public Collection<? extends String> getHas_family_history() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_FAMILY_HISTORY, String.class);
    }

    public boolean hasHas_family_history() {
		return !getHas_family_history().isEmpty();
    }

    public void addHas_family_history(String newHas_family_history) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_FAMILY_HISTORY, newHas_family_history);
    }

    public void removeHas_family_history(String oldHas_family_history) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_FAMILY_HISTORY, oldHas_family_history);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_previous_ocular_diesase
     */
     
    public Collection<? extends Object> getHas_previous_ocular_diesase() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_PREVIOUS_OCULAR_DIESASE, Object.class);
    }

    public boolean hasHas_previous_ocular_diesase() {
		return !getHas_previous_ocular_diesase().isEmpty();
    }

    public void addHas_previous_ocular_diesase(Object newHas_previous_ocular_diesase) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_PREVIOUS_OCULAR_DIESASE, newHas_previous_ocular_diesase);
    }

    public void removeHas_previous_ocular_diesase(Object oldHas_previous_ocular_diesase) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_PREVIOUS_OCULAR_DIESASE, oldHas_previous_ocular_diesase);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_sex
     */
     
    public Collection<? extends String> getHas_sex() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_SEX, String.class);
    }

    public boolean hasHas_sex() {
		return !getHas_sex().isEmpty();
    }

    public void addHas_sex(String newHas_sex) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_SEX, newHas_sex);
    }

    public void removeHas_sex(String oldHas_sex) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_SEX, oldHas_sex);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_trauma
     */
     
    public Collection<? extends String> getHas_trauma() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_TRAUMA, String.class);
    }

    public boolean hasHas_trauma() {
		return !getHas_trauma().isEmpty();
    }

    public void addHas_trauma(String newHas_trauma) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_TRAUMA, newHas_trauma);
    }

    public void removeHas_trauma(String oldHas_trauma) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_TRAUMA, oldHas_trauma);
    }


}
