package Ontology.impl;

import Ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultPRESENCE_of_DISEASES <br>
 * @version generated on Mon Nov 02 00:41:38 WAT 2015 by oyindolapo
 */
public class DefaultPRESENCE_of_DISEASES extends WrappedIndividualImpl implements PRESENCE_of_DISEASES {

    public DefaultPRESENCE_of_DISEASES(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





}
