package Ontology.impl;

import Ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultOPTIC_NERVE <br>
 * @version generated on Mon Nov 02 00:41:37 WAT 2015 by oyindolapo
 */
public class DefaultOPTIC_NERVE extends WrappedIndividualImpl implements OPTIC_NERVE {

    public DefaultOPTIC_NERVE(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_ocular_opticNerve
     */
     
    public Collection<? extends String> getHas_ocular_opticNerve() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_OCULAR_OPTICNERVE, String.class);
    }

    public boolean hasHas_ocular_opticNerve() {
		return !getHas_ocular_opticNerve().isEmpty();
    }

    public void addHas_ocular_opticNerve(String newHas_ocular_opticNerve) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_OCULAR_OPTICNERVE, newHas_ocular_opticNerve);
    }

    public void removeHas_ocular_opticNerve(String oldHas_ocular_opticNerve) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_OCULAR_OPTICNERVE, oldHas_ocular_opticNerve);
    }


}
