package Ontology.impl;

import Ontology.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultLENS_CLARITY <br>
 * @version generated on Mon Nov 02 00:41:37 WAT 2015 by oyindolapo
 */
public class DefaultLENS_CLARITY extends WrappedIndividualImpl implements LENS_CLARITY {

    public DefaultLENS_CLARITY(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_clarity
     */
     
    public Collection<? extends String> getHas_clarity() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_CLARITY, String.class);
    }

    public boolean hasHas_clarity() {
		return !getHas_clarity().isEmpty();
    }

    public void addHas_clarity(String newHas_clarity) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_CLARITY, newHas_clarity);
    }

    public void removeHas_clarity(String oldHas_clarity) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HAS_CLARITY, oldHas_clarity);
    }


}
