package Ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: AGE <br>
 * @version generated on Mon Nov 02 00:41:37 WAT 2015 by oyindolapo
 */

public interface AGE extends EVALUATION_OF_RESULTS {

    /* ***************************************************
     * Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_age
     */
     
    /**
     * Gets all property values for the has_age property.<p>
     * 
     * @returns a collection of values for the has_age property.
     */
    Collection<? extends Integer> getHas_age();

    /**
     * Checks if the class has a has_age property value.<p>
     * 
     * @return true if there is a has_age property value.
     */
    boolean hasHas_age();

    /**
     * Adds a has_age property value.<p>
     * 
     * @param newHas_age the has_age property value to be added
     */
    void addHas_age(Integer newHas_age);

    /**
     * Removes a has_age property value.<p>
     * 
     * @param oldHas_age the has_age property value to be removed.
     */
    void removeHas_age(Integer oldHas_age);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
