package Ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: CORNEAL_THICKNESS <br>
 * @version generated on Mon Nov 02 00:41:37 WAT 2015 by oyindolapo
 */

public interface CORNEAL_THICKNESS extends EVALUATION_OF_RESULTS {

    /* ***************************************************
     * Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_corneal_thickness
     */
     
    /**
     * Gets all property values for the has_corneal_thickness property.<p>
     * 
     * @returns a collection of values for the has_corneal_thickness property.
     */
    Collection<? extends String> getHas_corneal_thickness();

    /**
     * Checks if the class has a has_corneal_thickness property value.<p>
     * 
     * @return true if there is a has_corneal_thickness property value.
     */
    boolean hasHas_corneal_thickness();

    /**
     * Adds a has_corneal_thickness property value.<p>
     * 
     * @param newHas_corneal_thickness the has_corneal_thickness property value to be added
     */
    void addHas_corneal_thickness(String newHas_corneal_thickness);

    /**
     * Removes a has_corneal_thickness property value.<p>
     * 
     * @param oldHas_corneal_thickness the has_corneal_thickness property value to be removed.
     */
    void removeHas_corneal_thickness(String oldHas_corneal_thickness);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
