package Ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: FAMILY_HISTORY <br>
 * @version generated on Mon Nov 02 00:41:37 WAT 2015 by oyindolapo
 */

public interface FAMILY_HISTORY extends EVALUATION_OF_RESULTS {

    /* ***************************************************
     * Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_family_history
     */
     
    /**
     * Gets all property values for the has_family_history property.<p>
     * 
     * @returns a collection of values for the has_family_history property.
     */
    Collection<? extends String> getHas_family_history();

    /**
     * Checks if the class has a has_family_history property value.<p>
     * 
     * @return true if there is a has_family_history property value.
     */
    boolean hasHas_family_history();

    /**
     * Adds a has_family_history property value.<p>
     * 
     * @param newHas_family_history the has_family_history property value to be added
     */
    void addHas_family_history(String newHas_family_history);

    /**
     * Removes a has_family_history property value.<p>
     * 
     * @param oldHas_family_history the has_family_history property value to be removed.
     */
    void removeHas_family_history(String oldHas_family_history);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
