package Ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: IOP <br>
 * @version generated on Mon Nov 02 00:41:37 WAT 2015 by oyindolapo
 */

public interface IOP extends EVALUATION_OF_RESULTS {

    /* ***************************************************
     * Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#IOP_level
     */
     
    /**
     * Gets all property values for the IOP_level property.<p>
     * 
     * @returns a collection of values for the IOP_level property.
     */
    Collection<? extends Integer> getIOP_level();

    /**
     * Checks if the class has a IOP_level property value.<p>
     * 
     * @return true if there is a IOP_level property value.
     */
    boolean hasIOP_level();

    /**
     * Adds a IOP_level property value.<p>
     * 
     * @param newIOP_level the IOP_level property value to be added
     */
    void addIOP_level(Integer newIOP_level);

    /**
     * Removes a IOP_level property value.<p>
     * 
     * @param oldIOP_level the IOP_level property value to be removed.
     */
    void removeIOP_level(Integer oldIOP_level);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
