package Ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: OCULAR_EXAMINATION_and_HISTORY <br>
 * @version generated on Mon Nov 02 00:41:37 WAT 2015 by oyindolapo
 */

public interface OCULAR_EXAMINATION_and_HISTORY extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_task
     */
     
    /**
     * Gets all property values for the has_task property.<p>
     * 
     * @returns a collection of values for the has_task property.
     */
    Collection<? extends WrappedIndividual> getHas_task();

    /**
     * Checks if the class has a has_task property value.<p>
     * 
     * @return true if there is a has_task property value.
     */
    boolean hasHas_task();

    /**
     * Adds a has_task property value.<p>
     * 
     * @param newHas_task the has_task property value to be added
     */
    void addHas_task(WrappedIndividual newHas_task);

    /**
     * Removes a has_task property value.<p>
     * 
     * @param oldHas_task the has_task property value to be removed.
     */
    void removeHas_task(WrappedIndividual oldHas_task);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
