package Ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: OPTIC_NERVE <br>
 * @version generated on Mon Nov 02 00:41:37 WAT 2015 by oyindolapo
 */

public interface OPTIC_NERVE extends EVALUATION_OF_RESULTS {

    /* ***************************************************
     * Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_ocular_opticNerve
     */
     
    /**
     * Gets all property values for the has_ocular_opticNerve property.<p>
     * 
     * @returns a collection of values for the has_ocular_opticNerve property.
     */
    Collection<? extends String> getHas_ocular_opticNerve();

    /**
     * Checks if the class has a has_ocular_opticNerve property value.<p>
     * 
     * @return true if there is a has_ocular_opticNerve property value.
     */
    boolean hasHas_ocular_opticNerve();

    /**
     * Adds a has_ocular_opticNerve property value.<p>
     * 
     * @param newHas_ocular_opticNerve the has_ocular_opticNerve property value to be added
     */
    void addHas_ocular_opticNerve(String newHas_ocular_opticNerve);

    /**
     * Removes a has_ocular_opticNerve property value.<p>
     * 
     * @param oldHas_ocular_opticNerve the has_ocular_opticNerve property value to be removed.
     */
    void removeHas_ocular_opticNerve(String oldHas_ocular_opticNerve);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
