package Ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: PATIENT_INFORMATION <br>
 * @version generated on Mon Nov 02 00:41:37 WAT 2015 by oyindolapo
 */

public interface PATIENT_INFORMATION extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_entry_point
     */
     
    /**
     * Gets all property values for the has_entry_point property.<p>
     * 
     * @returns a collection of values for the has_entry_point property.
     */
    Collection<? extends WrappedIndividual> getHas_entry_point();

    /**
     * Checks if the class has a has_entry_point property value.<p>
     * 
     * @return true if there is a has_entry_point property value.
     */
    boolean hasHas_entry_point();

    /**
     * Adds a has_entry_point property value.<p>
     * 
     * @param newHas_entry_point the has_entry_point property value to be added
     */
    void addHas_entry_point(WrappedIndividual newHas_entry_point);

    /**
     * Removes a has_entry_point property value.<p>
     * 
     * @param oldHas_entry_point the has_entry_point property value to be removed.
     */
    void removeHas_entry_point(WrappedIndividual oldHas_entry_point);


    /* ***************************************************
     * Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_uniqueness
     */
     
    /**
     * Gets all property values for the has_uniqueness property.<p>
     * 
     * @returns a collection of values for the has_uniqueness property.
     */
    Collection<? extends WrappedIndividual> getHas_uniqueness();

    /**
     * Checks if the class has a has_uniqueness property value.<p>
     * 
     * @return true if there is a has_uniqueness property value.
     */
    boolean hasHas_uniqueness();

    /**
     * Adds a has_uniqueness property value.<p>
     * 
     * @param newHas_uniqueness the has_uniqueness property value to be added
     */
    void addHas_uniqueness(WrappedIndividual newHas_uniqueness);

    /**
     * Removes a has_uniqueness property value.<p>
     * 
     * @param oldHas_uniqueness the has_uniqueness property value to be removed.
     */
    void removeHas_uniqueness(WrappedIndividual oldHas_uniqueness);


    /* ***************************************************
     * Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_Firstname
     */
     
    /**
     * Gets all property values for the has_Firstname property.<p>
     * 
     * @returns a collection of values for the has_Firstname property.
     */
    Collection<? extends String> getHas_Firstname();

    /**
     * Checks if the class has a has_Firstname property value.<p>
     * 
     * @return true if there is a has_Firstname property value.
     */
    boolean hasHas_Firstname();

    /**
     * Adds a has_Firstname property value.<p>
     * 
     * @param newHas_Firstname the has_Firstname property value to be added
     */
    void addHas_Firstname(String newHas_Firstname);

    /**
     * Removes a has_Firstname property value.<p>
     * 
     * @param oldHas_Firstname the has_Firstname property value to be removed.
     */
    void removeHas_Firstname(String oldHas_Firstname);



    /* ***************************************************
     * Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_ID
     */
     
    /**
     * Gets all property values for the has_ID property.<p>
     * 
     * @returns a collection of values for the has_ID property.
     */
    Collection<? extends Object> getHas_ID();

    /**
     * Checks if the class has a has_ID property value.<p>
     * 
     * @return true if there is a has_ID property value.
     */
    boolean hasHas_ID();

    /**
     * Adds a has_ID property value.<p>
     * 
     * @param newHas_ID the has_ID property value to be added
     */
    void addHas_ID(Object newHas_ID);

    /**
     * Removes a has_ID property value.<p>
     * 
     * @param oldHas_ID the has_ID property value to be removed.
     */
    void removeHas_ID(Object oldHas_ID);



    /* ***************************************************
     * Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_address
     */
     
    /**
     * Gets all property values for the has_address property.<p>
     * 
     * @returns a collection of values for the has_address property.
     */
    Collection<? extends String> getHas_address();

    /**
     * Checks if the class has a has_address property value.<p>
     * 
     * @return true if there is a has_address property value.
     */
    boolean hasHas_address();

    /**
     * Adds a has_address property value.<p>
     * 
     * @param newHas_address the has_address property value to be added
     */
    void addHas_address(String newHas_address);

    /**
     * Removes a has_address property value.<p>
     * 
     * @param oldHas_address the has_address property value to be removed.
     */
    void removeHas_address(String oldHas_address);



    /* ***************************************************
     * Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_age
     */
     
    /**
     * Gets all property values for the has_age property.<p>
     * 
     * @returns a collection of values for the has_age property.
     */
    Collection<? extends Integer> getHas_age();

    /**
     * Checks if the class has a has_age property value.<p>
     * 
     * @return true if there is a has_age property value.
     */
    boolean hasHas_age();

    /**
     * Adds a has_age property value.<p>
     * 
     * @param newHas_age the has_age property value to be added
     */
    void addHas_age(Integer newHas_age);

    /**
     * Removes a has_age property value.<p>
     * 
     * @param oldHas_age the has_age property value to be removed.
     */
    void removeHas_age(Integer oldHas_age);



    /* ***************************************************
     * Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_allergy
     */
     
    /**
     * Gets all property values for the has_allergy property.<p>
     * 
     * @returns a collection of values for the has_allergy property.
     */
    Collection<? extends String> getHas_allergy();

    /**
     * Checks if the class has a has_allergy property value.<p>
     * 
     * @return true if there is a has_allergy property value.
     */
    boolean hasHas_allergy();

    /**
     * Adds a has_allergy property value.<p>
     * 
     * @param newHas_allergy the has_allergy property value to be added
     */
    void addHas_allergy(String newHas_allergy);

    /**
     * Removes a has_allergy property value.<p>
     * 
     * @param oldHas_allergy the has_allergy property value to be removed.
     */
    void removeHas_allergy(String oldHas_allergy);



    /* ***************************************************
     * Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_educational_level
     */
     
    /**
     * Gets all property values for the has_educational_level property.<p>
     * 
     * @returns a collection of values for the has_educational_level property.
     */
    Collection<? extends String> getHas_educational_level();

    /**
     * Checks if the class has a has_educational_level property value.<p>
     * 
     * @return true if there is a has_educational_level property value.
     */
    boolean hasHas_educational_level();

    /**
     * Adds a has_educational_level property value.<p>
     * 
     * @param newHas_educational_level the has_educational_level property value to be added
     */
    void addHas_educational_level(String newHas_educational_level);

    /**
     * Removes a has_educational_level property value.<p>
     * 
     * @param oldHas_educational_level the has_educational_level property value to be removed.
     */
    void removeHas_educational_level(String oldHas_educational_level);



    /* ***************************************************
     * Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_family_history
     */
     
    /**
     * Gets all property values for the has_family_history property.<p>
     * 
     * @returns a collection of values for the has_family_history property.
     */
    Collection<? extends String> getHas_family_history();

    /**
     * Checks if the class has a has_family_history property value.<p>
     * 
     * @return true if there is a has_family_history property value.
     */
    boolean hasHas_family_history();

    /**
     * Adds a has_family_history property value.<p>
     * 
     * @param newHas_family_history the has_family_history property value to be added
     */
    void addHas_family_history(String newHas_family_history);

    /**
     * Removes a has_family_history property value.<p>
     * 
     * @param oldHas_family_history the has_family_history property value to be removed.
     */
    void removeHas_family_history(String oldHas_family_history);



    /* ***************************************************
     * Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_previous_ocular_diesase
     */
     
    /**
     * Gets all property values for the has_previous_ocular_diesase property.<p>
     * 
     * @returns a collection of values for the has_previous_ocular_diesase property.
     */
    Collection<? extends Object> getHas_previous_ocular_diesase();

    /**
     * Checks if the class has a has_previous_ocular_diesase property value.<p>
     * 
     * @return true if there is a has_previous_ocular_diesase property value.
     */
    boolean hasHas_previous_ocular_diesase();

    /**
     * Adds a has_previous_ocular_diesase property value.<p>
     * 
     * @param newHas_previous_ocular_diesase the has_previous_ocular_diesase property value to be added
     */
    void addHas_previous_ocular_diesase(Object newHas_previous_ocular_diesase);

    /**
     * Removes a has_previous_ocular_diesase property value.<p>
     * 
     * @param oldHas_previous_ocular_diesase the has_previous_ocular_diesase property value to be removed.
     */
    void removeHas_previous_ocular_diesase(Object oldHas_previous_ocular_diesase);



    /* ***************************************************
     * Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_sex
     */
     
    /**
     * Gets all property values for the has_sex property.<p>
     * 
     * @returns a collection of values for the has_sex property.
     */
    Collection<? extends String> getHas_sex();

    /**
     * Checks if the class has a has_sex property value.<p>
     * 
     * @return true if there is a has_sex property value.
     */
    boolean hasHas_sex();

    /**
     * Adds a has_sex property value.<p>
     * 
     * @param newHas_sex the has_sex property value to be added
     */
    void addHas_sex(String newHas_sex);

    /**
     * Removes a has_sex property value.<p>
     * 
     * @param oldHas_sex the has_sex property value to be removed.
     */
    void removeHas_sex(String oldHas_sex);



    /* ***************************************************
     * Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_trauma
     */
     
    /**
     * Gets all property values for the has_trauma property.<p>
     * 
     * @returns a collection of values for the has_trauma property.
     */
    Collection<? extends String> getHas_trauma();

    /**
     * Checks if the class has a has_trauma property value.<p>
     * 
     * @return true if there is a has_trauma property value.
     */
    boolean hasHas_trauma();

    /**
     * Adds a has_trauma property value.<p>
     * 
     * @param newHas_trauma the has_trauma property value to be added
     */
    void addHas_trauma(String newHas_trauma);

    /**
     * Removes a has_trauma property value.<p>
     * 
     * @param oldHas_trauma the has_trauma property value to be removed.
     */
    void removeHas_trauma(String oldHas_trauma);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
