package Ontology;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: PRESENCE_of_DISEASES <br>
 * @version generated on Mon Nov 02 00:41:38 WAT 2015 by oyindolapo
 */

public interface PRESENCE_of_DISEASES extends EVALUATION_OF_RESULTS {

    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
