package Ontology;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Mon Nov 02 00:41:37 WAT 2015 by oyindolapo
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#AGE
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AGE.<p>
     * 
     */
    public static final OWLClass CLASS_AGE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#AGE"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#CATARACT
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CATARACT.<p>
     * 
     */
    public static final OWLClass CLASS_CATARACT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#CATARACT"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#CLASSIFICATION_and_PREDICTION
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CLASSIFICATION_AND_PREDICTION.<p>
     * 
     */
    public static final OWLClass CLASS_CLASSIFICATION_AND_PREDICTION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#CLASSIFICATION_and_PREDICTION"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#COMORBID
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMORBID.<p>
     * 
     */
    public static final OWLClass CLASS_COMORBID = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#COMORBID"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#CONSULTATION
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONSULTATION.<p>
     * 
     */
    public static final OWLClass CLASS_CONSULTATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#CONSULTATION"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#CORNEAL_THICKNESS
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CORNEAL_THICKNESS.<p>
     * 
     */
    public static final OWLClass CLASS_CORNEAL_THICKNESS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#CORNEAL_THICKNESS"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#CP_ENTRY
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CP_ENTRY.<p>
     * 
     */
    public static final OWLClass CLASS_CP_ENTRY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#CP_ENTRY"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#DECISIONS
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DECISIONS.<p>
     * 
     */
    public static final OWLClass CLASS_DECISIONS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#DECISIONS"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#EVALUATION_OF_RESULTS
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EVALUATION_OF_RESULTS.<p>
     * 
     */
    public static final OWLClass CLASS_EVALUATION_OF_RESULTS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#EVALUATION_OF_RESULTS"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#FAMILY_HISTORY
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FAMILY_HISTORY.<p>
     * 
     */
    public static final OWLClass CLASS_FAMILY_HISTORY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#FAMILY_HISTORY"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#FEEDBACK
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FEEDBACK.<p>
     * 
     */
    public static final OWLClass CLASS_FEEDBACK = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#FEEDBACK"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#GLAUCOMA
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GLAUCOMA.<p>
     * 
     */
    public static final OWLClass CLASS_GLAUCOMA = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#GLAUCOMA"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#IOP
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IOP.<p>
     * 
     */
    public static final OWLClass CLASS_IOP = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#IOP"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#LENS_CLARITY
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LENS_CLARITY.<p>
     * 
     */
    public static final OWLClass CLASS_LENS_CLARITY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#LENS_CLARITY"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#NONE
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NONE.<p>
     * 
     */
    public static final OWLClass CLASS_NONE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#NONE"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#OCULAR_EXAMINATION_and_HISTORY
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OCULAR_EXAMINATION_AND_HISTORY.<p>
     * 
     */
    public static final OWLClass CLASS_OCULAR_EXAMINATION_AND_HISTORY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#OCULAR_EXAMINATION_and_HISTORY"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#OPTIC_NERVE
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OPTIC_NERVE.<p>
     * 
     */
    public static final OWLClass CLASS_OPTIC_NERVE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#OPTIC_NERVE"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#PATIENT_EDUCATION
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PATIENT_EDUCATION.<p>
     * 
     */
    public static final OWLClass CLASS_PATIENT_EDUCATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#PATIENT_EDUCATION"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#PATIENT_INFORMATION
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PATIENT_INFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_PATIENT_INFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#PATIENT_INFORMATION"));

    /* ***************************************************
     * Class http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#PRESENCE_of_DISEASES
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRESENCE_OF_DISEASES.<p>
     * 
     */
    public static final OWLClass CLASS_PRESENCE_OF_DISEASES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#PRESENCE_of_DISEASES"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_Decision
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_DECISION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_DECISION = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_Decision"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_action
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_ACTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_ACTION = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_action"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_cataract
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_CATARACT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_CATARACT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_cataract"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_comorbid
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_COMORBID.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_COMORBID = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_comorbid"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_entry_point
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_ENTRY_POINT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_ENTRY_POINT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_entry_point"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_glaucoma
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_GLAUCOMA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_GLAUCOMA = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_glaucoma"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_none
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_NONE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_NONE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_none"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_task
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_TASK.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_TASK = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_task"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_uniqueness
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_UNIQUENESS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_UNIQUENESS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_uniqueness"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#is_followed_by_task
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_FOLLOWED_BY_TASK.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_FOLLOWED_BY_TASK = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#is_followed_by_task"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#topObjectProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TOPOBJECTPROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TOPOBJECTPROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#topObjectProperty"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#IOP_level
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property IOP_LEVEL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_IOP_LEVEL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#IOP_level"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_Firstname
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_FIRSTNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_FIRSTNAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_Firstname"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_ID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_ID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_ID = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_ID"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_address
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_ADDRESS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_ADDRESS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_address"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_age
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_AGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_AGE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_age"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_allergy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_ALLERGY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_ALLERGY = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_allergy"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_clarity
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_CLARITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_CLARITY = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_clarity"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_corneal_thickness
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_CORNEAL_THICKNESS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_CORNEAL_THICKNESS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_corneal_thickness"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_educational_level
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_EDUCATIONAL_LEVEL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_EDUCATIONAL_LEVEL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_educational_level"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_family_history
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_FAMILY_HISTORY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_FAMILY_HISTORY = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_family_history"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_lastname
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_LASTNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_LASTNAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_lastname"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_ocular_opticNerve
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_OCULAR_OPTICNERVE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_OCULAR_OPTICNERVE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_ocular_opticNerve"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_previous_ocular_diesase
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_PREVIOUS_OCULAR_DIESASE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_PREVIOUS_OCULAR_DIESASE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_previous_ocular_diesase"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_sex
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_SEX.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_SEX = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_sex"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_trauma
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_TRAUMA.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_TRAUMA = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/oyindolapo/ontologies/2015/9/updated_ontology#has_trauma"));


}
